// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLbxKUCd272S9_Jui02vNBaiQyfiM8-yg',
    appId: '1:192668855025:web:a3567fc553c6d24864d750',
    messagingSenderId: '192668855025',
    projectId: 'puff-pal',
    authDomain: 'puff-pal.firebaseapp.com',
    storageBucket: 'puff-pal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu0N6T_RSzLLxNp2GuKUZc5eOR5PWMrG8',
    appId: '1:192668855025:android:d588de2ff1dac32a64d750',
    messagingSenderId: '192668855025',
    projectId: 'puff-pal',
    storageBucket: 'puff-pal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZSy2srJcLk_lxjSUJirZbTY1QtzrmKog',
    appId: '1:192668855025:ios:7e3eb31d63ed9a8e64d750',
    messagingSenderId: '192668855025',
    projectId: 'puff-pal',
    storageBucket: 'puff-pal.firebasestorage.app',
    iosBundleId: 'com.example.puffpal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZSy2srJcLk_lxjSUJirZbTY1QtzrmKog',
    appId: '1:192668855025:ios:7e3eb31d63ed9a8e64d750',
    messagingSenderId: '192668855025',
    projectId: 'puff-pal',
    storageBucket: 'puff-pal.firebasestorage.app',
    iosBundleId: 'com.example.puffpal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLbxKUCd272S9_Jui02vNBaiQyfiM8-yg',
    appId: '1:192668855025:web:c6712a9d999b856264d750',
    messagingSenderId: '192668855025',
    projectId: 'puff-pal',
    authDomain: 'puff-pal.firebaseapp.com',
    storageBucket: 'puff-pal.firebasestorage.app',
  );

}